- name: ec2 launcher
  hosts: localhost
  connection: local
  become: False
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
          key_name: aws_master_key
          instance_type: t2.micro
          image: ami-0747bdcabd34c712a
          region: us-east-2
          group: default
          vpc_subnet_id: default
          wait: yes
          count: 1
          assign_public_ip: yes

