# Basic provisioning example
- hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
          key_name: aws_instance_Ansible
          instance_type: t2.micro
          image: ami-0dacb0c129b49f529
          region: us-east-2
          wait: yes
          wait_timeout: 500
          group: Ansible
          count: 1
          assign_public_ip: yes

